name: Build

on:
  push:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libjsoncpp-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
          make
          strip --strip-unneeded oceanpop
          mkdir AppDir
          make install DESTDIR=Appdir
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oceanpop-linux
          path: |
            *.AppImage
            LICENSE.txt
            README.md

  Windows:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          vcpkg install --triplet x64-windows sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-mixer[mpg123] jsoncpp
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -D-DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
          cp LICENSE.txt Release
          cp README.md Release
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oceanpop-windows
          path: |
            Release

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - name: Install dependencies
        run: |
          apk add cmake gmp mpc1 mpfr4 make
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir oceanpop
          cd oceanpop
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
          cp ../LICENSE.txt ./
          cp ../README.md ./
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oceanpop-psp
          path: |
            oceanpop/EBOOT.PBP
            oceanpop/assets
            oceanpop/LICENSE.txt
            oceanpop/README.md

  Vita:
    runs-on: ubuntu-latest
    container: gnuton/vitasdk-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="${VITASDK}/share/vita.toolchain.cmake" .
          make
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oceanpop-vita
          path: |
            oceanpop.vpk
            LICENSE.txt
            README.md

  Publish:
    needs: [Linux, Windows, PSP, Vita]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [linux, windows, psp, vita]
    steps:
    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/download-artifact@v2
    - name: Zip artifacts
      run: |
        zip -r oceanpop-${{matrix.build}}.zip oceanpop-${{matrix.build}}
    - name: Create pre-release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: oceanpop-${{matrix.build}}.zip
        prerelease: true
        name: "Development build"
        tag_name: "latest"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: oceanpop-${{matrix.build}}.zip
        tag_name: ${{ steps.tag.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
