name: Build

on:
  push:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libjsoncpp-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make
          strip --strip-unneeded match-theory
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: match-theory-ubuntu
          path: |
            match-theory
            assets
            LICENSE
            README.md

  Windows:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          vcpkg install --triplet x64-windows sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-mixer[libvorbis,mpg123] jsoncpp
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -D-DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: match-theory-windows
          path: |
            Debug
            Release
            LICENSE
            README.md

  PSP:
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add make cmake
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir match-theory
          cd match-theory
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
          cp ../LICENSE ./
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: match-theory-psp
          path: |
            match-theory/EBOOT.pbp
            match-theory/assets
            match-theory/LICENSE
            README.md

  Vita:
    container: gnuton/vitasdk-docker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="${VITASDK}/share/vita.toolchain.cmake" .
          make
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: match-theory-vita
          path: |
            match-theory.vpk
            LICENSE
            README.md
            
